<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Go to Tradeshow</name>
   <tag></tag>
   <elementGuidId>50c5e2e8-383c-41a6-ae1a-090583b09635</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Tradeshow Entrance']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.et-waypoint.et_pb_animation_top.wp-image-1368.et-animated</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1200</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>450</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://staging.orderease.show/wp-content/uploads/2020/11/manchester-buttons4.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Tradeshow Entrance</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://staging.orderease.show/wp-content/uploads/2020/11/manchester-buttons4.jpg 1200w, https://staging.orderease.show/wp-content/uploads/2020/11/manchester-buttons4-980x368.jpg 980w, https://staging.orderease.show/wp-content/uploads/2020/11/manchester-buttons4-480x180.jpg 480w</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(min-width: 0px) and (max-width: 480px) 480px, (min-width: 481px) and (max-width: 980px) 980px, (min-width: 981px) 1200px, 100vw</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>et-waypoint et_pb_animation_top wp-image-1368 et-animated</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;logo-scroller-carousel&quot;)/div[@class=&quot;et_pb_row et_pb_row_1 et_pb_row_5col&quot;]/div[@class=&quot;et_pb_column et_pb_column_1_5 et_pb_column_1  et_pb_css_mix_blend_mode_passthrough&quot;]/div[@class=&quot;et_pb_with_border et_pb_module et_pb_blurb et_pb_blurb_0 et_clickable  et_pb_text_align_left  et_pb_blurb_position_top et_pb_bg_layout_light&quot;]/div[@class=&quot;et_pb_blurb_content&quot;]/div[@class=&quot;et_pb_main_blurb_image&quot;]/span[@class=&quot;et_pb_image_wrap&quot;]/img[@class=&quot;et-waypoint et_pb_animation_top wp-image-1368 et-animated&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='logo-scroller-carousel']/div/div/div/div/div/span/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Tradeshow Entrance']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/span/img</value>
   </webElementXpaths>
</WebElementEntity>
